### ISSUE TITLE
Separate `Settings` types for workers and clients

### ISSUE THREAD

**Issue by liftM** [freckle/faktory_worker_haskell#49]
Although it makes sense that workers internally call `newClient` and use the same underlying client type as job producers, this makes for a very confusing API for newcomers. Here are some points of confusion I had:

- Why does `Settings` have a `Queue`? What does this do when I'm using the client to push jobs? What if the job itself has its own `Queue`? Do I need a separate client for every queue I want to push to?
- Why does `Settings` have a `Maybe WorkerId`? How do I use this with `runWorker`? What does this do when I'm using this client to push jobs?

I would prefer if there were clearer, separate APIs for the role of a job consumer and a job producer. In my mind, there should be "Producer" and "Consumer" abstractions that both use a lower-level "Client" implementation (that people can use to send raw commands, etc.).

**Comment by pbrisbin** [comment]
Thanks very much for reporting this and your two other Issues. I'm going to reply to all three here, at least to start.

> makes for a very confusing API for newcomers

I don't disagree. I also wonder if getting the README rendering in the Haddocks would help here, since I think that clarifies the [overall usage](https://github.com/freckle/faktory_worker_haskell#usage), but is not currently visible when you arrive at the docs through Hackage.

Additionally, I think we should add a top-level `Faktory` module that re-exports a cleaner, more obvious API for both Production and Consumption. We probably erred on the side of defining less to start, so that we didn't lock ourselves into an API that wasn't right. I think we're starting to see what is "right" now, and so could take a stab at laying out some surface area.

> Why does Settings have a Queue?

Historical accident. It was/is needed for `runWorker`, and so got lumped into `Settings` before production was really fully designed.

> What does this do when I'm using the client to push jobs?

Ignored, AFAIK.

> What if the job itself has its own Queue?

That is what's used. And if _not_, Faktory itself sends it to a queue named `Default` (which I dislike, FWIW).

> Do I need a separate client for every queue I want to push to?

Nope.

> Why does Settings have a Maybe WorkerId?

`Settings` does not, but `newClient` does. We use a `Just` value for consumption clients and a `Nothing` for producers. `newClient` wasn't really intended as external API, but it slipped out since we never built a nicer Producer function. `runWorker` is really the external Consumer API, but of course you run into #47 and #48 when you work at that level.

>  How do I use this with runWorker?

You don't, `runWorker` handles it internally (which causes #47).

>  What does this do when I'm using this client to push jobs?

The Worker Id is sent in the Hello payload to Faktory, and that's it. I don't actually know what Faktory does if you create a client with an explicit Worker Id and then only use it to push Jobs. I'd imagine nothing, since it's just a bit of metadata that Faktory keeps around but only uses/displays in consumer-focused UIs.

> I would prefer if there were clearer, separate APIs for the role of a job consumer and a job producer

Sounds completely reasonable to me! I think this should solve all three issues you've reported. I don't actually know how to set a Worker Name with Faktory, but I assume it's possible. So if we add a `Maybe WorkerName` in whatever Consumer Settings abstraction we create, we'd solve #48 as well.

**Question for the team**: how do we all feel about "Snoyman-style" settings as a pattern, i.e. `default(Producer|Consumer)Settings` plus functions like `setWorkerName`? Personally, in the context of this project, I think I'd use plain records, and am fine with bumping major version as much as it churns, vs defining all these functions to allow minor-only additions and internal changes in the future -- but I don't feel strongly.

**Comment by pbrisbin** [comment]
One hiccup, as I look back over the _Architecture overview_ that all Faktory clients seem to contain (including ours):

It seems Faktory uses the terms _Client_ (who pushes) and _Worker_ (who pulls), and a _Worker_ is just a particular way to use a _Client_. I don't love this, as far as architectural naming is concerned, since following it faithfully in our code has led to exactly the confusions described in this issue. Having _Producer_ and _Consumer_ abstractions (and hiding the fact that both are _Client_s) seems much clearer (as you've said). However, for us to do that, we'd be sort of inventing our own terminology that doesn't appear in the official Faktory docs or those of any other clients -- so I'm hesitant. Are we OK with that?

**Comment by cdparks** [comment]
Having first-class Producer and Consumer abstractions sounds nice to me

**Comment by pbrisbin** [comment]
Between #50 and #51, I believe this is now resolved:

- A `Producer` is a `Client` who (only) produces and a Worker is a `Client` who (only) consumes
- `Settings` can be thought of as `Client` settings, so they apply to (and are passed when constructing) `Producer`s or Workers
- `WorkerSettings` are (surprise) the Worker-specific settings
- Those now include an optional `WorkerId` (solving #47)

This will be a major bump because of the changed Settings interfaces. I'd like to give some time for #48 before releasing it; but my current sense is that it's not possible, so I'll proceed with release next week if there's no new information on it.
